name:                knotTheory
version:             0.1.0.0
github:              "phro/knotTheory"
license:             GPL3
author:              "Jesse Frohlich"
maintainer:          "frohlich@math.toronto.edu"
copyright:           "2021 Jesse Frohlich"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/phro/knotTheory#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

# executables:
  # knotTheory-exe:
    # main:                Main.hs
    # source-dirs:         app
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    # dependencies:
    # - knotTheory

tests:
  knotTheory-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knotTheory
